---

- name: check composer
  stat:
    path: /usr/local/bin/composer
  register: composer_bin
  tags: composer

- block:
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: install composer
    become: yes
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin

  - name: rename composer.phar to composer
    become: yes
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

  - name: make composer executable
    become: yes
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file

  - name: add composer path
    lineinfile:
      path: /home/vagrant/.bash_profile
      regexp: ^PATH=$PATH:$HOME/.local/bin:$HOME/bin
      line: "PATH=$HOME/.composer/vendor/bin:$PATH:$HOME/.local/bin:$HOME/bin"

  when: not composer_bin.stat.exists
  tags: composer

- name: install php-cs-fixer
  become: yes
  become_user: vagrant
  shell: |
    export COMPOSER_PROCESS_TIMEOUT=1200
    export COMPOSER_HOME=/home/vagrant/.composer && composer global require friendsofphp/php-cs-fixer
  args:
    warn: no

- block:
  - name: mkdir ~/.composer/config
    file:
      path: /home/vagrant/.composer/config
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: cp php_cs.dist
    copy:
      src: php_cs.dist
      dest: /home/vagrant/.composer/config/.php_cs.dist
      owner: vagrant
      group: vagrant
      mode: 0644

  when: conf.php_version > 70
